apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  labels:
    name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          image: souravsharma035/locust:v1
          #          command: ["/bin/bash",  "-c", "-f /mnt/locust/pwa.py --master -H http://locust-master:8089"]
          env:
            - name: LOCUST_MODE
              value: master
            - name: TARGET_HOST
              value: locust-master
          volumeMounts:
            - name: pv-claim1
              mountPath: /mnt/locust

          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP

      volumes:
         - name: pv-claim1
           persistentVolumeClaim:
             claimName: pv-claim1

