apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1

spec:
  storageClassName: nfs
  accessModes: [ "ReadWriteOnce" ]
  capacity:
   storage: 1Gi
  nfs:
   server: 172.25.82.21       
   path: /home/devops/kubernetes-locust-example/locast_data

