version: '3'
services:
  devops-task2:
    build: .
    network_mode: host
    restart: on-failure
    cpu_period: 100000
    cpu_quota: 5000
    mem_limit: 100m
    environment:
      API_URL: http://127.0.0.1:5000/

